# This file was automatically generated by APIMATIC v2.0 on 06/23/2016

module MagicTelecomApi
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.magictelecom.com'

    # API Token
    @x_auth_token = ''123abcqwerty''

    # create the getters and setters
    class << self
      attr_accessor :BASE_URI

    end
  end
end
