# This file was automatically generated by APIMATIC v2.0 on 06/23/2016
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'magic_telecom_api/api_helper.rb'
require 'magic_telecom_api/api_exception.rb'
require 'magic_telecom_api/configuration.rb'
require 'magic_telecom_api/magic_telecom_api_client.rb'

# Controllers
require 'magic_telecom_api/controllers/users_controller.rb'
require 'magic_telecom_api/controllers/accounts_controller.rb'
require 'magic_telecom_api/controllers/dids_controller.rb'
require 'magic_telecom_api/controllers/dids_products_controller.rb'

# Models
require 'magic_telecom_api/models/cdrs.rb'
require 'magic_telecom_api/models/cart_checkout_form.rb'
require 'magic_telecom_api/models/checkout.rb'
require 'magic_telecom_api/models/token_form.rb'
require 'magic_telecom_api/models/account_form.rb'
require 'magic_telecom_api/models/cdr_form.rb'
require 'magic_telecom_api/models/trunk_form.rb'
require 'magic_telecom_api/models/trunk.rb'
require 'magic_telecom_api/models/routing.rb'
require 'magic_telecom_api/models/endpoint.rb'
require 'magic_telecom_api/models/caller_location.rb'
require 'magic_telecom_api/models/caller_location_form.rb'
require 'magic_telecom_api/models/account.rb'
require 'magic_telecom_api/models/telephone_number_form.rb'
require 'magic_telecom_api/models/item_form.rb'
require 'magic_telecom_api/models/item.rb'
require 'magic_telecom_api/models/routing_base.rb'
require 'magic_telecom_api/models/telephone_number.rb'
require 'magic_telecom_api/models/token.rb'
