# This file was automatically generated by APIMATIC v2.0 on 06/23/2016

require 'magic_telecom_api/models/item'

module MagicTelecomApi
  class LocationItem < Item 
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :location_handle

    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :quantity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :attributes

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :did_type_handle

    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :trunk_id

    # TODO: Write general description for this method
    # @return [CallerLocation]
    attr_accessor :caller_location

    def method_missing(method_name)
      puts "there's no method called '#{method_name}'"
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['location_handle'] = location_handle
      hash['quantity'] = quantity
      hash['attributes'] = attributes
      hash['did_type_handle'] = did_type_handle
      hash['trunk_id'] = trunk_id
      hash['_caller_location'] = caller_location
      hash = super().merge(hash) 
      hash
    end
  end
end
