# This file was automatically generated by APIMATIC v2.0 on 06/23/2016

require 'magic_telecom_api/models/routing_base'

module MagicTelecomApi
  class Routing < RoutingBase 
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sip_user

    def method_missing(method_name)
      puts "there's no method called '#{method_name}'"
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['sip_user'] = sip_user
      hash = super().merge(hash) 
      hash
    end
  end
end
