# This file was automatically generated by APIMATIC v2.0 on 06/23/2016

module MagicTelecomApi
  class TelephoneNumber
    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :trunk_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sip_end_point_uri

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :alias

    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :channels

    # TODO: Write general description for this method
    # @return [RoutingBase]
    attr_accessor :routing

    def method_missing(method_name)
      puts "there's no method called '#{method_name}'"
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['trunk_id'] = trunk_id
      hash['sip_end_point_uri'] = sip_end_point_uri
      hash['alias'] = alias
      hash['channels'] = channels
      hash['_routing'] = routing
      hash
    end
  end
end
