# This file was automatically generated by APIMATIC v2.0 on 06/23/2016

module MagicTelecomApi
  class Trunk
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :sip_end_point_uri

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [Routing]
    attr_accessor :routing

    def method_missing(method_name)
      puts "there's no method called '#{method_name}'"
    end

    # Creates JSON of the curent object
    def to_json
      hash = key_map
      hash.to_json
    end

    # Defines the key map for json serialization
    def key_map
      hash = {}
      hash['sip_end_point_uri'] = sip_end_point_uri
      hash['description'] = description
      hash['_routing'] = routing
      hash
    end
  end
end
